[package]
edition = "2021"
name = "thanks-contributors"
description = "This little script accesses GitHub's API to get all contributors and their PRs between two distinct points in the history of commits. This is helpful for changelogs where you'd want to list all contributions for that release (so e.g. changes between v1 and v1.1)."
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
clap = "3.0.14"
color-eyre = "0.6.0"
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.0.4", default-features = false, features = ["napi4"] }
napi-derive = "2.0.8"
reqwest = "0.11.9"
serde = "1.0.136"
serde_json = "1.0.78"
tokio = "1.16.1"

[build-dependencies]
napi-build = "1.2.1"

[profile.release]
lto = true
